language: go

go:
  - '1.13.x'

before_install:
  - chmod +x generatepb.sh


install:
  - go mod download
  - go get -v -d -t github.com/golang/protobuf/...
  - curl -L https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
  - go install github.com/golang/protobuf/protoc-gen-go
  - ./generatepb.sh

env:
  - PATH=$HOME/protoc/bin:$PATH;GO111MODULE=on

script:
  - make test
  - make build


notifications:
  email: false