language: go

env: GO111MODULE=on

go:
  - '1.13.x'

before_install:
  - mkdir "${HOME}/go"; export GOPATH="${HOME}/go";
  - chmod +x install_protoc.sh
  - chmod +x generatepb.sh
  - ./install_protoc.sh


install:
  - go mod download
  - ./generatepb.sh

script:
  - make test
  - make build


notifications:
  email: false