language: go

env: GO111MODULE=on

go:
  - '1.13.x'

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

before_script:
  - ./generatepb.sh

script:
  - go test -v ./...