language: go

env: GO111MODULE=on

go:
  - '1.13.x'

before_install:
  - mkdir "${HOME}/go"; export GOPATH="${HOME}/go";


install:
  - go mod download
  - ./install_protoc.sh
  - ./generatepb.sh

script:
  - make test
  - make build